version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:1406@db:5432/Discord
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "3000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1406
      - POSTGRES_DB=Discord
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 