-- Adiciona novas colunas de configuração na tabela bot_configs
ALTER TABLE bot_configs
ADD COLUMN IF NOT EXISTS log_command_usage BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS respond_to_mentions BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS delete_command_messages BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS enable_welcome_messages BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS enable_goodbye_messages BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS enable_auto_role BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS enable_logging BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS enable_anti_spam BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS enable_auto_mod BOOLEAN DEFAULT TRUE; 